### ISSUE TITLE
gzip: chictopia.sql.gz: not in gzip format

### ISSUE THREAD

**Issue by hrsma2i** [kyamagu/paperdoll#12]
I executed the following along with [this page](https://github.com/kyamagu/paperdoll/tree/master/data/chictopia), but it doesn't work.

`gunzip -c chictopia.sql.gz | sqlite3 chictopia.sqlite3`

I caught the following error.

`gzip: chictopia.sql.gz: not in gzip format`

**Comment by kyamagu** [comment]
@hrsma2i Please check if the gzip file is correctly fetched.

```
$ md5 chictopia.sql.gz 
MD5 (chictopia.sql.gz) = 069f6eee95856380da5c2181b58bd65d
```

**Comment by hrsma2i** [comment]
I didn't use `git lfs`.
I directly downloaded `chictopia.sql.gz` and it worked.
