### ISSUE TITLE
How to get images in train.json and val.json from photos.lmdb

### ISSUE THREAD

**Issue by Hliang1994** [kyamagu/paperdoll#13]
Hello, I am a new learner of ModaNet. I would like to know how can I get the 52,377 images in 'modanet2018_instances_train.json' and 2799 images in 'modanet2018_instances_val.json' from 'photos.lmdb' and 'chictopia.sqlite3'. Thanks a lot!

**Comment by kyamagu** [comment]
See [usage](https://github.com/kyamagu/paperdoll/blob/master/data/chictopia/usage.ipynb)
