### ISSUE TITLE
Dumping the feature vectors before PCA and SVM

### ISSUE THREAD

**Issue by phui** [kyamagu/paperdoll#8]
First, thank you very much for your help over https://github.com/kyamagu/mexopencv/issues/339 . I and my teammates have been playing around with PaperDoll ever since. I am a PhD student working in team of four, trying to explore CV applications in fashion industry. If this thread goes too long here, I am hoping we can communicate through email instead.

We are applying PaperDoll on our collected datasets from different sources. The main challenge occurs in corping the image so that each corped part contains only one person, then setting the right threshold for pose estimation.

We are at the stage where we would like to dump the features being fed to PCA and SVM for some inspection. In the `feature_calculator` code, I understand that `config` object is being used to tell the script what parts of the pipeline to run.

Is there a way for us to stop the pipeline and dump the features acquired (maybe in a csv file) before PCA and SVM?

Many many thanks.

**Comment by kyamagu** [comment]
@phui Just trim the `config` array to the point you want to stop: i.e., `config(1:3)` if you want to stop at the third step. You should get any intermediate data in the result struct.

**Comment by phui** [comment]
@kyamagu Thank you very much for your reply! We are able to dump the features in the middle of the pipeline by triming the `config` as you suggested.

One follow-up question: We saw a struct called `style_descriptor2`. We think it is the projection result from PCA. Can you verify our conjecture?

**Comment by kyamagu** [comment]
@phui 

> One follow-up question: We saw a struct called style_descriptor2. We think it is the projection result from PCA. Can you verify our conjecture?

Yes, it is the projection result.

**Comment by phui** [comment]
@kyamagu Bravo! Thank you very much for your help. I will be working on this project over the summer also. Hopefully it goes well.

よろしくおねがいします。
